spring.application.name=lutetiaWebshop
spring.datasource.url=jdbc:postgresql://localhost:5432/lutetiashop
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create-drop

server.error.include-message=always
server.port=8080
server.servlet.context-path=/api